name: ci
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
permissions:
  contents: read
jobs:
  ci:
    if: always() && !cancelled()
    needs:
      - job0
      - job1
      - integration
      - tag0
      - tag1
    runs-on: ubuntu-slim
    steps:
      - env:
          integration_ok: ${{ github.event_name == 'pull_request' && needs.integration.result == 'success' || needs.integration.result == 'skipped' }}
          tag0_ok: ${{ github.ref_type == 'tag' && needs.tag0.result == 'success' || needs.tag0.result == 'skipped '}}
          tag1_ok: ${{ github.ref_type == 'tag' && needs.tag1.result == 'success' || needs.tag1.result == 'skipped '}}
        run: |
          printf '::notice::running %s.\n' "${{ github.job}}"

          set -x

          printf '${{ needs.tag0.result }}
          printf '${{ needs.tag1.result }}
          printf '${{ needs.integration.result }}

          test "${integration_ok}" = true
          test "${tag0_ok}" = true
          test "${tag1_ok}" = true
  job0:
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  job1:
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  integration:
    if: always() && !cancelled()
    needs:
      - integration0
      - integration1
    runs-on: ubuntu-slim
    steps:
      - env:
          integration0_ok: ${{ github.event_name == 'pull_request' && needs.integration0.result == 'success' || needs.integration0.result == 'skipped' }}
          integration1_ok: ${{ github.event_name == 'pull_request' && needs.integration1.result == 'success' || needs.integration1.result == 'skipped' }}
        run: |
          printf '::notice::running %s.\n' "${{ github.job}}"

          set -x

          printf '${{ needs.integration0.result }}
          printf '${{ needs.integration1.result }}

          test "${integration0_ok}" = true
          test "${integration1_ok}" = true
  integration0:
    if: github.event_name == 'pull_request'
    needs: job0
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  integration1:
    if: github.event_name == 'pull_request'
    needs:
      - job0
      - job1
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  tag0:
    if: github.ref_type == 'tag'
    needs:
      - job0
      - job1
      - integration
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  tag1:
    if: github.ref_type == 'tag'
    needs: tag0
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
