name: ci
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
permissions:
  contents: read
jobs:
  ci:
    needs:
      - job0
      - job1
      - integration0
      - integration1
      - tag0
      - tag1
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  job0:
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  job1:
    runs-on: ubuntu-slim
    steps:
      - run: printf '::notice::running %s.\n' "${{ github.job}}"
  integration0:
    needs: job0
    runs-on: ubuntu-slim
    steps:
      - if: github.event_name != 'pull_request'
        run: printf '::notice::skipped %s.\n' "${{ github.job}}"
      - if: github.event_name == 'pull_request'
        run: printf '::notice::running %s.\n' "${{ github.job}}"
  integration1:
    needs:
      - job0
      - job1
    runs-on: ubuntu-slim
    steps:
      - if: github.event_name != 'pull_request'
        run: printf '::notice::skipped %s.\n' "${{ github.job}}"
      - if: github.event_name == 'pull_request'
        run: printf '::notice::running %s.\n' "${{ github.job}}"
  tag0:
    needs:
      - job0
      - job1
      - integration0
      - integration1
    runs-on: ubuntu-slim
    steps:
      - if: github.ref_type != 'tag'
        run: printf '::notice::skipped %s.\n' "${{ github.job}}"
      - if: github.ref_type == 'tag'
        run: printf '::notice::running %s.\n' "${{ github.job}}"
  tag1:
    needs: tag0
    runs-on: ubuntu-slim
    steps:
      - if: github.ref_type != 'tag'
        run: printf '::notice::skipped %s.\n' "${{ github.job}}"
      - if: github.ref_type == 'tag'
        run: printf '::notice::running %s.\n' "${{ github.job}}" && false
